# TASK 1 · Exploratory Data Analysis (EDA) on Retail Sales Data
**Oasis Infobyte Data Analytics Internship — Task Level 1**

* **Objective:** Perform a thorough Exploratory Data Analysis on a retail sales dataset to uncover patterns, customer behavior trends, and actionable business insights.  
* **Tech Stack:** Python 3, Pandas, NumPy, Matplotlib, Seaborn, Jupyter Notebook  

---

### Feature Checklist
* [x] **Load dataset and perform initial inspection:** shape, column dtypes, null value check
* [ ] **Descriptive statistics:** mean, median, mode, standard deviation for all numerical columns
* [ ] **Time series analysis:** plot monthly and quarterly sales trends using line charts
* [ ] **Customer demographics analysis:** distribution of customer age groups, gender breakdown
* [ ] **Product analysis:** top 10 best-selling products; revenue by product category (bar chart)
* [ ] **Heatmap:** correlation matrix between numerical variables
* [ ] **At least one additional visualisation:** reveals a non-obvious insight
* [ ] **Markdown cells throughout notebook:** written observations after each chart
* [ ] **Conclusion section:** at least 3 specific, actionable business recommendations based on findings

## 1. Environment Setup & Library Imports
We import the foundational Python libraries for data wrangling (`pandas`, `numpy`) and data visualization (`matplotlib`, `seaborn`).

In [1]:
import os
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configure display and styling preferences
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 11

print("Environment setup completed successfully.")

Environment setup completed successfully.

## 2. Dataset Ingestion
We load the retail sales dataset from the `Data/` directory. If running from the subfolder `01-retail-sales-eda/`, the file path is resolved relative to the parent directory.

In [2]:
# Dynamically resolve dataset path
data_dir = os.path.join("..", "Data") if os.path.exists(os.path.join("..", "Data")) else "Data"
file_name = "retail_sales_dataset.csv"
dataset_path = os.path.join(data_dir, file_name)

print(f"Loading dataset from: {os.path.abspath(dataset_path)}")

# Load the dataset into a pandas DataFrame
df = pd.read_csv(dataset_path)

print(f"Dataset successfully loaded into DataFrame.")
print(f"Total Rows: {df.shape[0]:,}")
print(f"Total Columns: {df.shape[1]}")

Loading dataset from: C:\Users\Iba Zaidi\Desktop\OIBSIP\DataAnalytics-L1-EDARetailSales\Data\retail_sales_dataset.csv
Dataset successfully loaded into DataFrame.
Total Rows: 1,000
Total Columns: 9

## 3. Initial Data Inspection & Hygiene Check

In this initial phase, we inspect:
1. **First & Last Records:** Preview actual data values and format.
2. **Data Types & Memory:** Check data types assigned by Pandas.
3. **Missing / Null Values:** Check for any incomplete records.
4. **Duplicate Records:** Check for redundant transaction rows.
5. **Feature Cardinality:** Number of unique values per column.

### 3.1 First 10 Records Preview

In [3]:
# Display the first 10 transactions
df.head(10)

   Transaction ID        Date Customer ID  Gender  Age Product Category  Quantity  Price per Unit  Total Amount
0               1  2023-11-24     CUST001    Male   34           Beauty         3              50           150
1               2  2023-02-27     CUST002  Female   26         Clothing         2             500          1000
2               3  2023-01-13     CUST003    Male   50      Electronics         1              30            30
3               4  2023-05-21     CUST004    Male   37         Clothing         1             500           500
4               5  2023-05-06     CUST005    Male   30           Beauty         2              50           100
5               6  2023-04-25     CUST006  Female   45           Beauty         1              30            30
6               7  2023-03-13     CUST007    Male   46         Clothing         2              25            50
7               8  2023-02-22     CUST008    Male   30      Electronics         4              25           100
8               9  2023-12-13     CUST009    Male   63      Electronics         2             300           600
9              10  2023-10-07     CUST010  Female   52         Clothing         4              50           200

### 3.2 Last 5 Records Preview

In [4]:
# Display the last 5 transactions
df.tail(5)

     Transaction ID        Date Customer ID  Gender  Age Product Category  Quantity  Price per Unit  Total Amount
995             996  2023-05-16     CUST996    Male   62         Clothing         1              50            50
996             997  2023-11-17     CUST997    Male   52           Beauty         3              30            90
997             998  2023-10-29     CUST998  Female   23           Beauty         4              25           100
998             999  2023-12-05     CUST999  Female   36      Electronics         3              50           150
999            1000  2023-04-12    CUST1000    Male   47      Electronics         4              30           120

### 3.3 DataFrame Information & Schema Inspection

In [5]:
# Column names, non-null counts, and memory usage
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 100.2 KB

### 3.4 Missing / Null Value Audit

In [6]:
# Count and percentage of missing values per column
missing_df = pd.DataFrame({
    'Column': df.columns,
    'Missing Values': df.isnull().sum().values,
    'Missing Percentage (%)': (df.isnull().sum().values / len(df)) * 100
})
missing_df.sort_values(by='Missing Values', ascending=False).reset_index(drop=True)

             Column  Missing Values  Missing Percentage (%)
0    Transaction ID               0                     0.0
1              Date               0                     0.0
2       Customer ID               0                     0.0
3            Gender               0                     0.0
4               Age               0                     0.0
5  Product Category               0                     0.0
6          Quantity               0                     0.0
7    Price per Unit               0                     0.0
8      Total Amount               0                     0.0

### 3.5 Duplicate Records Verification

In [7]:
# Check for identical duplicate rows
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows in the dataset: {duplicate_count}")

# Check for uniqueness of primary key (Transaction ID)
unique_transactions = df['Transaction ID'].nunique()
print(f"Unique Transaction IDs: {unique_transactions} out of {len(df)} rows")
assert unique_transactions == len(df), "Warning: Duplicate Transaction IDs detected!"
print("Verification Passed: Transaction ID is unique across all rows.")

Number of duplicate rows in the dataset: 0

Unique Transaction IDs: 1000 out of 1000 rows
Verification Passed: Transaction ID is unique across all rows.

### 3.6 Attribute Cardinality & Unique Values Summary

In [8]:
# Unique values and distinct counts per column
for col in df.columns:
    unique_vals = df[col].unique()
    num_unique = len(unique_vals)
    if num_unique <= 10:
        print(f"Column '{col}' ({num_unique} unique): {list(unique_vals)}")
    else:
        print(f"Column '{col}' ({num_unique} unique): sample {list(unique_vals[:3])}...")

Column 'Transaction ID' (1000 unique): sample [np.int64(1), np.int64(2), np.int64(3)]...
Column 'Date' (345 unique): sample ['2023-11-24', '2023-02-27', '2023-01-13']...
Column 'Customer ID' (1000 unique): sample ['CUST001', 'CUST002', 'CUST003']...
Column 'Gender' (2 unique): ['Male', 'Female']
Column 'Age' (47 unique): sample [np.int64(34), np.int64(26), np.int64(50)]...
Column 'Product Category' (3 unique): ['Beauty', 'Clothing', 'Electronics']
Column 'Quantity' (4 unique): [np.int64(3), np.int64(2), np.int64(1), np.int64(4)]
Column 'Price per Unit' (5 unique): [np.int64(50), np.int64(500), np.int64(30), np.int64(25), np.int64(300)]
Column 'Total Amount' (18 unique): sample [np.int64(150), np.int64(1000), np.int64(30)]...

### 3.7 Preliminary Descriptive Overview

In [9]:
# Initial 5-number summary and distribution of numerical columns
df.describe().T

                 count     mean         std   min     25%    50%     75%     max
Transaction ID  1000.0  500.500  288.819436   1.0  250.75  500.5  750.25  1000.0
Age             1000.0   41.392   13.681430  18.0   29.00   42.0   53.00    64.0
Quantity        1000.0    2.514    1.132734   1.0    1.00    3.0    4.00     4.0
Price per Unit  1000.0  179.890  189.681356  25.0   30.00   50.0  300.00   500.0
Total Amount    1000.0  456.000  559.997632  25.0   60.00  135.0  900.00  2000.0

## 4. Day 1 Observations & Initial Insights

> [!NOTE]
> ### Key Findings from Day 1 Inspection
> 1. **Data Completeness & Hygiene:**
>    - The dataset comprises **1,000 transactions** across **9 distinct attributes**.
>    - **Zero missing or null values** were detected across all columns.
>    - **Zero duplicate rows** were found; each row represents a strictly unique `Transaction ID` from 1 to 1,000.
> 
> 2. **Feature Attributes & Structure:**
>    - **Identifiers:** `Transaction ID` (unique integer 1–1000) and `Customer ID` (unique alphanumeric customer tags).
>    - **Temporal:** `Date` represents the purchase timestamp (spanning the 2023 calendar year). Currently stored as string/object type.
>    - **Customer Demographics:**
>      - `Gender`: Binary categorical feature (Male and Female shoppers).
>      - `Age`: Integer values spanning from **18 to 64 years**, with an average age of ~**41.4 years**.
>    - **Merchandise & Category:**
>      - `Product Category`: Three core retail lines: **`Clothing`**, **`Electronics`**, and **`Beauty`**.
>    - **Sales & Financials:**
>      - `Quantity`: Basket volume ranging from **1 to 4 units** (mean: 2.51 units).
>      - `Price per Unit`: Product pricing tiers ranging from **$25 to $500** (mean: $179.89).
>      - `Total Amount`: Basket spend ranging from **$25 to $2,000** (mean: $456.00). Note that `Total Amount = Quantity × Price per Unit`.